cloudflared:
  image:
    tag: 2023.6.1
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: k3s-homelab
    ingress:
      - hostname: '*.k3s.yovi.info'
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local
        originRequest:
          noTLSVerify: true
      - service: http_status:404

  podMonitor:
    enabled: true
    metricsEndpoints:
      - port: http